config/routes.rb
Catering::Application.routes.draw do
  resources :homes

  devise_for :users

  resources :orders

  resources :caterers

  resources :confrooms

  resources :depts

    root :to => 'homes#index'

end

app/models/caterer.rb
class Caterer < ActiveRecord::Base
  attr_accessible :caterer_name
  has_many :orders
end

app/controllers/caterers_controller.rb
class CaterersController < ApplicationController
  # GET /caterers
  # GET /caterers.json
  def index
    @caterers = Caterer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @caterers }
    end
  end

  # GET /caterers/1
  # GET /caterers/1.json
  def show
    @caterer = Caterer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @caterer }
    end
  end

  # GET /caterers/new
  # GET /caterers/new.json
  def new
    @caterer = Caterer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @caterer }
    end
  end

  # GET /caterers/1/edit
  def edit
    @caterer = Caterer.find(params[:id])
  end

  # POST /caterers
  # POST /caterers.json
  def create
    @caterer = Caterer.new(params[:caterer])

    respond_to do |format|
      if @caterer.save
        format.html { redirect_to @caterer, notice: 'Caterer was successfully created.' }
        format.json { render json: @caterer, status: :created, location: @caterer }
      else
        format.html { render action: "new" }
        format.json { render json: @caterer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /caterers/1
  # PUT /caterers/1.json
  def update
    @caterer = Caterer.find(params[:id])

    respond_to do |format|
      if @caterer.update_attributes(params[:caterer])
        format.html { redirect_to @caterer, notice: 'Caterer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @caterer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caterers/1
  # DELETE /caterers/1.json
  def destroy
    @caterer = Caterer.find(params[:id])
    @caterer.destroy

    respond_to do |format|
      format.html { redirect_to caterers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/caterers_helper.rb
module CaterersHelper
end

app/views/caterers/_form.html.erb
<%= form_for @caterer, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :caterer_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :caterer_name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                caterers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/caterers/edit.html.erb
<%- model_class = Caterer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/caterers/index.html.erb
<%- model_class = Caterer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:caterer_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @caterers.each do |caterer| %>
      <tr>
        <td><%= link_to caterer.id, caterer_path(caterer) %></td>
        <td><%= caterer.caterer_name %></td>
        <td><%=l caterer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_caterer_path(caterer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      caterer_path(caterer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_caterer_path,
            :class => 'btn btn-primary' %>

app/views/caterers/new.html.erb
<%- model_class = Caterer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/caterers/show.html.erb
<%- model_class = Caterer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:caterer_name) %>:</strong></dt>
  <dd><%= @caterer.caterer_name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              caterers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_caterer_path(@caterer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              caterer_path(@caterer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>