config/routes.rb
Catering::Application.routes.draw do
  resources :homes

  devise_for :users

  resources :orders

  resources :caterers

  resources :confrooms

  resources :depts

    root :to => 'homes#index'

end

app/models/confroom.rb
class Confroom < ActiveRecord::Base
  attr_accessible :conf_room
  has_many :orders
end

app/controllers/confrooms_controller.rb
class ConfroomsController < ApplicationController
  # GET /confrooms
  # GET /confrooms.json
  def index
    @confrooms = Confroom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @confrooms }
    end
  end

  # GET /confrooms/1
  # GET /confrooms/1.json
  def show
    @confroom = Confroom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @confroom }
    end
  end

  # GET /confrooms/new
  # GET /confrooms/new.json
  def new
    @confroom = Confroom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @confroom }
    end
  end

  # GET /confrooms/1/edit
  def edit
    @confroom = Confroom.find(params[:id])
  end

  # POST /confrooms
  # POST /confrooms.json
  def create
    @confroom = Confroom.new(params[:confroom])

    respond_to do |format|
      if @confroom.save
        format.html { redirect_to @confroom, notice: 'Confroom was successfully created.' }
        format.json { render json: @confroom, status: :created, location: @confroom }
      else
        format.html { render action: "new" }
        format.json { render json: @confroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /confrooms/1
  # PUT /confrooms/1.json
  def update
    @confroom = Confroom.find(params[:id])

    respond_to do |format|
      if @confroom.update_attributes(params[:confroom])
        format.html { redirect_to @confroom, notice: 'Confroom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @confroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /confrooms/1
  # DELETE /confrooms/1.json
  def destroy
    @confroom = Confroom.find(params[:id])
    @confroom.destroy

    respond_to do |format|
      format.html { redirect_to confrooms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/confrooms_helper.rb
module ConfroomsHelper
end

app/views/confrooms/_form.html.erb
<%= form_for @confroom, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :conf_room, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :conf_room, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                confrooms_path, :class => 'btn' %>
  </div>
<% end %>

app/views/confrooms/edit.html.erb
<%- model_class = Confroom -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/confrooms/index.html.erb
<%- model_class = Confroom -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:conf_room) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @confrooms.each do |confroom| %>
      <tr>
        <td><%= link_to confroom.id, confroom_path(confroom) %></td>
        <td><%= confroom.conf_room %></td>
        <td><%=l confroom.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_confroom_path(confroom), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      confroom_path(confroom),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_confroom_path,
            :class => 'btn btn-primary' %>

app/views/confrooms/new.html.erb
<%- model_class = Confroom -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/confrooms/show.html.erb
<%- model_class = Confroom -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:conf_room) %>:</strong></dt>
  <dd><%= @confroom.conf_room %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              confrooms_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_confroom_path(@confroom), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              confroom_path(@confroom),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>