config/routes.rb
Catering::Application.routes.draw do
  resources :homes

  devise_for :users

  resources :orders

  resources :caterers

  resources :confrooms

  resources :depts

    root :to => 'homes#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_filter :set_home, only: [:show, :edit, :update, :destroy]

  def index
  end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<!DOCTYPE html>
<html ng-app="caterorder">
<head>
 </head>
<body ng-controller="DeptController as d"> 
<br/>
<br/>
 <table class="table table-striped table-bordered ">
    <thead>
      
        <th>Dept Name</th>
      
    </thead>
      <tbody>
      <tr ng-repeat="dept in d.depts">
        <td>{{dept.dept_name}}</td>
	<td><button ng-init="row=0" ng-click="action=2">Edit</button> 
<div ng-show="action==2">
 <blockquote>
  <form name="deptForm" ng-submit="d.editDept(dept)">
	<input type="hidden" ng-model="dept.id">
        <input type="text" ng-model="dept.dept_name">
	<input type="submit" value="Submit" />
  </form>
 </blockquote>
 </div></td>  
	<td><button ng-click="d.deleteDept(dept.id)">Delete</button></td>
      </tr>
    </tbody>
 </table>

 <blockquote>
  Add Dept
    <form name="deptForm"  ng-submit="d.addDept(dept)">
        <input ng-init="" type="text" ng-model="dept.dept_name">
	<input type="submit" value="Submit" />
    </form>
  </blockquote>  
</body>
</html>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>