config/routes.rb
Catering::Application.routes.draw do
  resources :homes

  devise_for :users

  resources :orders

  resources :caterers

  resources :confrooms

  resources :depts

    root :to => 'homes#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="caterorder">
<head>
  <title>Catering</title>
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
          <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
            <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                              <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                                  <span class="icon-bar"></span>
                                                          </a>
                                                                  <a class="brand" href="#">Catering</a>
                                                                          <div class="nav-collapse">
                                                                                    <ul class="nav">

<li><%= link_to "Orders", orders_path %></li>

<%# if current_user.role == 'Admin' %>

<li><%= link_to "Depts", depts_path  %></li>
                                                                                                            <li><%= link_to "Caterer", caterers_path %></li>
                                                                                                                        <li><%= link_to "Conference Rooms", confrooms_path %></li>

<%# end %>

<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %> </strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>                                                                                                                                    
                                                                                                                                              </ul>
                                                                                                                                                      </div>
                                                                                                                                                            </div>
                                                                                                                                                                </div>
                                                                                                                                                                  </div>
<p class="navbar-text pull-right">
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<div class="container">
    <div class="row">
          <div class="span9">
		  <%= yield %>
    </div>
                <div class="span3">
                        <h2>About Us</h2>
                                Lorem ipsum dolor sit amet, consect
                                      </div>
                                          </div>
                                            </div>

</body>
</html>